{
  'env_length': 2,
  'env_width': 2,
  'n_hider': 1,
  'n_searcher': 1,
  'dt': 0.2,
  'max_step': 400,
  'queue_maxlen': 6,
  'queue_takelen': 5,
  'history_len': 1,
  'hider_size': 0.2,
  'hider_search_range': 20.5,      
  'hider_max_vel': 1.0,
  'searcher_size': 0.2,
  'searcher_search_range': 20.5,   
  'searcher_max_vel': 0.3
}